title: The Rock Orchestra
description: Digital playbill for The Rock Orchestra, 2026 Fall Tour, by The Great Unmasking.
lang: en

# If you publish as a project site (username.github.io/repo-name), you can
# optionally set: baseurl: "/repo-name"
# No setting is needed for a user site or a custom domain.

exclude:
  - README.md
